# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:15.12.0

pipelines:
  default:
    - step:
        name: 'Install'
        script:
          - yarn
    - step:
        name: 'Lint'
        script:
          - yarn run ui:lint
